name: CI for karsajobs-ui

on:
  push:
    branches:
      - karsajobs-ui

jobs:
  lint-dockerfile:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install hadolint
        run: |
          wget https://github.com/hadolint/hadolint/releases/download/v2.7.0/hadolint-Linux-x86_64
          chmod +x hadolint-Linux-x86_64
          sudo mv hadolint-Linux-x86_64 /usr/local/bin/hadolint
        shell: bash

      - name: Lint Dockerfile
        run: hadolint Dockerfile

  build-app-karsajobs-ui:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/karsajobs-ui:${{ github.sha }} .
          docker push ghcr.io/${{ github.repository }}/karsajobs-ui:${{ github.sha }}
#